version: '3.8'

services:
  web:
    build: ./
    image: rescuers
    command: python manage.py runserver --insecure 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    expose:
      - '8000'
    env_file:
      - ./.env.dev


