# Generated by Django 3.2.9 on 2021-12-22 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('standard_size', models.PositiveSmallIntegerField(verbose_name='Штатный размер')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('operative', models.BooleanField(verbose_name='Принадлежность к оперативному составу')),
                ('rescuer', models.BooleanField(verbose_name='Принадлежность к аттестованным спасателям')),
                ('attestation_period', models.CharField(max_length=20, verbose_name='Время между аттестациями для должности(если необходимо)')),
                ('service_in_name', models.CharField(blank=True, choices=[('мед', 'мед'), ('проф', 'проф'), ('опер', 'опер')], default='', help_text='Добавить при необходимости', max_length=12, verbose_name='Служба (для вывода в названии должности)')),
                ('priority', models.PositiveSmallIntegerField(blank=True, default=9, help_text='Для командира отряда- 1; Для зам.ком. отряда - 2; Для пом.ком. отряда - 3; Для ком. взвода     - 4; Для зам.ком.взвода  - 5; Для пом.ком. взвода - 6; Для ком.отдел.      - 7; Для респираторщика  - 8; Для остальных по умолчанию - 9.', verbose_name='Приоритет вывода в списке')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Служба',
                'verbose_name_plural': 'Службы',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('sex', models.CharField(blank=True, choices=[('МУЖ', 'МУЖ'), ('ЖЕН', 'ЖЕН')], default='МУЖ', max_length=6, null=True, verbose_name='Пол')),
                ('date_beginning', models.DateField(blank=True, null=True, verbose_name='Время начала службы')),
                ('date_attestation', models.DateField(blank=True, default=None, null=True, verbose_name='Дата последней аттестации')),
                ('on_duty', models.BooleanField(blank=True, default=False, null=True, verbose_name='Фактическое нахождение на службе')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='workers/', verbose_name='Фото')),
                ('attestated', models.BooleanField(blank=True, default=False, null=True, verbose_name='Аттестован')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_workers', to='workers.division', verbose_name='Подразделение')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_workers', to='workers.post', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['post__priority'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_posts', to='workers.service'),
        ),
        migrations.CreateModel(
            name='PostState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_size', models.PositiveSmallIntegerField(default=0, verbose_name='Штатный размер должности в подразделении')),
                ('slug', models.SlugField(editable=False, max_length=10, verbose_name='Идентификатор')),
                ('division', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_state', to='workers.division', verbose_name='Подразделение')),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_state', to='workers.post', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Штатный размер должности',
                'verbose_name_plural': 'Штатные размеры должностей',
                'unique_together': {('division', 'post')},
            },
        ),
    ]
