# Generated by Django 3.2.9 on 2021-12-23 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_remove_post_attestation_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_posts', to='workers.service', verbose_name='Служба'),
        ),
    ]
